### ISSUE TITLE
0.44 release libs not available on Jcentre

### ISSUE THREAD

**Issue by tomb50** [copper-leaf/kodiak#18]
Hello,

I'm trying to pull Orchid v0.18.2 but it's failing when trying to pull a dependency from jcenter (or jfrog rather) relating to this repo.

The following artifacts could not be resolved: 
com.eden.kodiak:common-models:jar:0.4.4, 
com.eden.kodiak:common-runner:jar:0.4.4: 

I've tried manually looking up the jar link from mvn repository too and it does indeed 404.

https://mvnrepository.com/artifact/com.eden.kodiak/common-models/0.4.4

or directly:

https://jcenter.bintray.com/com/eden/kodiak/common-models/0.4.4/common-models-0.4.4.jar

Are those libs being hosted elsewhere now?

Thanks!
Tom

**Comment by cjbrooks12** [comment]
Thanks for the heads-up. I botched a release last night, but it should be fixed now.
