### ISSUE TITLE
How could I use this

### ISSUE THREAD

**Issue by Tiagoperes** [copper-leaf/kodiak#20]
Hello, could you help me to use this lib? I read the documentation and couldn't get it to work. I currently have a project fully documented with dokka and it exports all of it in html files, used to build [this site](https://docs-reference.usebeagle.io/android/).

The documentation states which dependency I should add to include the functionality, but after that it just shows me a piece of code without telling me where to put it. Where exactly should I write the following?

```kotlin
var cacheDir: Path = Files.createTempDirectory("dokkaCache")
val runner: KotlindocInvoker = KotlindocInvokerImpl(cacheDir)

val outputDir = File("build/dokka").canonicalFile.toPath()
outputDir.toFile().deleteRecursively()
outputDir.toFile().mkdirs()

val rootDoc = runner.getRootDoc(
    listOf(
        File("widgets/src/main").canonicalFile.toPath(),
        File("kotlin-core/src/main/kotlin").canonicalFile.toPath()
    ),
    outputDir
) { inputStream -> IOStreamUtils.InputStreamPrinter(inputStream, null) }

rootDoc.packages.forEach { processPackage(it) }
rootDoc.classes.forEach { processClass(it) }
```

After writing this, which task should I call in gradle to generate the documentation in json? Do you have any example of how to add this to a project?

PS: I'm not using kotlin script for gradle, is it necessary?

Thank you in advance for the attention given to this

**Comment by cjbrooks12** [comment]
Kodiak is not a Gradle plugin, it's a JVM library. You'd add it to any normal JVM application and include the snippet above in that application. It was designed to not be part of the Gradle build because it's used in [Orchid](https://github.com/orchidhq/Orchid), which isn't itself tied to Gradle or any other build tool.
