### ISSUE TITLE
Cannot install version 0.3.x from JCenter

### ISSUE THREAD

**Issue by drochetti** [copper-leaf/kodiak#9]
When trying to use Kodiak directly as a dependency I cannot get version `0.3.5` (or any 0.3.x) while version `0.2.4` is pulled correctly.

Using `0.2.4`:

```groovy
implementation "com.eden:dokka-runner:0.2.4" // works! jars are pulled as expected
```

Using `0.3.5`:

```groovy
implementation "com.eden.kodiak:dokka-runner:0.3.5"
```

I get the following message:

```plain
Could not find com.eden.kodiak:dokka-runner:0.3.5.
Searched in the following locations:
  - https://jcenter.bintray.com/com/eden/kodiak/dokka-runner/0.3.5/dokka-runner-0.3.5.pom
  - https://jcenter.bintray.com/com/eden/kodiak/dokka-runner/0.3.5/dokka-runner-0.3.5.jar
  - https://repo.maven.apache.org/maven2/com/eden/kodiak/dokka-runner/0.3.5/dokka-runner-0.3.5.pom
  - https://repo.maven.apache.org/maven2/com/eden/kodiak/dokka-runner/0.3.5/dokka-runner-0.3.5.jar
```

Weird, because when I browse JCenter it seems like the version was published there.

This library is pretty cool and fits my use-case perfectly. I need to use the Models directly (not via Orchid) to get some documentation metadata from Kotlin files in a tool I'm working on. I'm more than happy to contribute back as I work with it.

Right now I need version `0.3.5` so I have access to `model.comments` as a `DocComment` instead of a `String`.

Thanks!

**Comment by cjbrooks12** [comment]
It's great to see another use-case for this project beyond Orchid, that's exactly why I extracted it here! 

I'll look into why that package isn't in jCenter, will likely need to get in touch with Bintray support which might take a few days. I've had this issue happen a number of times, where packages show that they're linked to jCenter but can't actually be resolved. The support team needs to go in and fix it manually, unfortunately.

Until I get this fixed, you can add the local repository link to your build and it should resolve fine.

```
repositories {
    ...
    maven { url "https://dl.bintray.com/javaeden/Eden" }
}
```

**Comment by drochetti** [comment]
Thanks for the fast response!

Using the local repository worked great =)
